USE [Bible]
GO

/****** Object:  Table [dbo].[KJV]    Script Date: 8/12/2024 2:06:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KJV](
	[text] [varchar](600) NOT NULL,
	[verse] [int] NOT NULL,
	[chapter] [int] NOT NULL,
	[book] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[book] ASC,
	[chapter] ASC,
	[verse] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

